### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Altmeris** [TonisGaming/Leatherworks#3]
Sorry, i wasnt able to find another way to connect except opening issue. First of all i want to say that this mod is great and i really love it!
Since it adding a way to gather flour would you consider a way to get salt/Cooking oil? I cant really imagine any way to gather salt since there's no salt caves and you cant get specifically sea water (every water is just snow-dirty water) but i can imagine way to get some"oil", you definitely can use animal fats (i hope i translated it right and you understand what i mean) to fry things, maybe add tallow that you getting when scrape fresh hide or get it as additional loot when harvesting meat (may be only for specific animals like rabbits or ptarmigans) and when you get enough tallow you can combine and "cook" it to get oil? Im suggesting it because not every recipe with flour need salt but as far as i know every recipe with flour need oil and there's no any way to get it except looting.

 p.s. for some reasons (maybe its just for me) you cant see improved flight jacket on character in clothing screen
 
 Thank you for attention! Love your mods :D

**Comment by TonisGaming** [comment]
Salt is renewable through the mod Bountiful Foraging, which lets you find halite (salt rocks) that can be crushed into salt.
Cooking oil can be made with the Tool Upgrade mod, if you have Candlelight installed and the Candlelight version of Tool Upgrade. There's a crafting recipe to turn fat into cooking oil (In the next update I'm gonna change the amount, cause it's currently a bit too cheap). Character clothing I'll look into.

Hopefully this helps

**Comment by Altmeris** [comment]
Thanks for fast answer!
